name: Pipeline

on: [push]
env:
  APPLICATION_NAME: app2
  DEPLOYMENT_NAME: dinuka
  GKE_CLUSTER: dinuka-cluster

jobs:



  deploy:
    runs-on: ubuntu-latest
    steps:
 

    - name: Set up GCloud
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '274.0.1'
        service_account_email: ${{ secrets.GCP_SERVICE_ACCT_EMAIL }}
        service_account_key: ${{ secrets.GCP_SERVICE_ACCT_KEY }}
      

      
    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
        helm version
        

        

    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER \
          --zone ${{ secrets.GCP_REGION }} \
          --project ${{ secrets.GCP_PROJECT_ID }}


        helm repo add bitnami https://charts.bitnami.com/bitnami

        kubectl create ns din
        helm install dinuka-release bitnami/kube-state-metrics -n din

        
        helm upgrade $DEPLOYMENT_NAME dinuka-release bitnami/ \
          --set app2.image.tag=latest\
          --wait -n din
        kubectl rollout status deployment/$DEPLOYMENT_NAME
        kubectl get services -o wide

        




