name: Pipeline

on: [push]
env:
  APPLICATION_NAME: app2
  GKE_PROJECT: randocats -- 
  GKE_EMAIL: ${{ secrets.GKE_EMAIL }}
  GITHUB_SHA: ${{ github.sha }}
  GKE_ZONE: us-east1-a
  GKE_CLUSTER: dinuka-cluster
  IMAGE: randocats
  REGISTRY_HOSTNAME: us.gcr.io
  DEPLOYMENT_NAME: randocats
  
jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python environment
      uses: actions/setup-python@v2
    - name: Install requirements
      run: pip install --quiet --requirement requirements.txt
    - name: Lint code
      run: |
        flake8 --ignore=E501,E231 *.py
        pylint --disable=C0301 --disable=C0326 *.py
    - name: Run unit tests
      run: |
        python -m unittest --verbose --failfast

  build_image:
    needs: [lint]
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up GCloud
      uses: google-github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SERVICE_ACCT_KEY }}
        export_default_credentials: true
    - run: |
        gcloud info
        
      # Install helm
    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
        
    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER \
          --zone $GKE_ZONE \
          --project $APPLICATION_NAME
        helm upgrade $APPLICATION_NAME $APPLICATION_NAME-cluster/ \
          --set randocats.image.tag=$GITHUB_SHA \
          --wait
        kubectl rollout status deployment/$DEPLOYMENT_NAME
        kubectl get services -o wide
       
        


