name: Pipeline

on: [push]
env:
  APPLICATION_NAME: app2
  DEPLOYMENT_NAME: dinuka_deploy

jobs:



  deploy:

    runs-on: ubuntu-latest
    steps:
    - name: Set up GCloud
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '274.0.1'
        service_account_email: ${{ secrets.GCP_SERVICE_ACCT_EMAIL }}
        service_account_key: ${{ secrets.GCP_SERVICE_ACCT_KEY }}
    - name: Install Helm
      run: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
      
    - run: |
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        gcloud config set run/region ${{ secrets.GCP_REGION }}
        gcloud info
        
      
    - name: Deploy in GKE
      run: |

        kubectl rollout status deployment/$DEPLOYMENT_NAME
        kubectl get services -o wide




